### ISSUE TITLE
Additional Features Request

### ISSUE THREAD

**Issue by jlmurphysa** [houssemELbahri/react-native-swipeable-container#2]
Hi there. We're looking to use this component for our application.

Currently, it has some limitations:

1. The button is visible behind the semi-transparent card item
2. We'd like swiping far left to expand the delete button and trigger delete (if swiping past a certain threshold)
3. We need an `activationThreshold` (or similar), so that the swipe is not triggered unintentionally when the user is trying to reorder sets (by grabbing the ordering handle and dragging up or down)

I see you started the project recently. Are these some things that you'd be looking to implement, and if so, would you like some help?

The limitations mentioned above are demonstrated here:

https://github.com/houssemELbahri/react-native-swipeable-container/assets/6492155/61fcad5d-89aa-4d4e-bb3e-fee692daa1ae

**Comment by houssemELbahri** [comment]
Thanks @melhawnuhra  for you feedback,.
Actually you can fix the first point by wrapping your content by another View and making the background of that view as white , 
for second point i'm working on that feature and it will be published very soon ,
for the third point i will check it and find a solution .

**Comment by jlmurphysa** [comment]
Many thanks, @houssemELbahri,

1. I think you're right that it's not a library limitation with the underlay being visible behind a transparent element - we can address it outselves.
2. Great to hear! Eagerly awaiting it, but we can probably go live without it temporarily.
3. This one is more urgent, as it would break the drag-and-drop-to-reorder feature for us, so we can't go live without it.

I appreciate the prompt feedback. Keep up the great work!

**Comment by jlmurphysa** [comment]
Update on this:

1. Managed to resolve by setting our foreground component to have an opaque background.
2. Swipe-to-delete works now, but would be nice to have the background expand with the swipe (but not critical for now)
3. Still needed, as drag-to-reorder is very difficult to use at the moment.

**Comment by jlmurphysa** [comment]
All addressed, as of 0.0.9 👍 Many thanks!
