### ISSUE TITLE
Animation of Delete (like the swipe) when clicking on Delete button

### ISSUE THREAD

**Issue by jlmurphysa** [houssemELbahri/react-native-swipeable-container#4]
**Is your feature request related to a problem? Please describe.**
Delete animation is inconsistent (swiping deletes gradually, clicking deletes immediately)

**Describe the solution you'd like**
When clicking the deleting button (as opposed to sliding), it should animate the removal of the element.

**Describe alternatives you've considered**
Leaving it like it is, but would be nicer animated.

**Additional context**
The two delete animations compared:
https://github.com/houssemELbahri/react-native-swipeable-container/assets/6492155/0e364b30-078a-4321-a624-f3855c391009

**Comment by houssemELbahri** [comment]
Thanks @melhawnuhra  for your feedback ,
Actually i’m working on that and it will be published very soon .

**Comment by houssemELbahri** [comment]
Available in version **0.0.8**
