### ISSUE TITLE
Delete button still visible after setting `swipeable=false`

### ISSUE THREAD

**Issue by jlmurphysa** [houssemELbahri/react-native-swipeable-container#5]
**Describe the bug**
When dynamically setting the `swipeable` prop to `false`, the button does not go away.
I think it should animate back to the closed (unswiped) state?

**To Reproduce**
1. Render an item with `swipeable=true`
2. Swipe so that the delete button is visible
3. Set `swipeable=false`
4. Observe the item is still in the swipe open state.

**Expected behavior**
The container should reset to closed (maybe via animation?).

**Screenshots**
Screen recording attached:

https://github.com/houssemELbahri/react-native-swipeable-container/assets/6492155/157fb661-9d2e-4079-8615-6db10d9936b7

**Smartphone:**
 - Device: iPhone 15 Pro

**Additional Context**
My SwipeableView Component:
```
        <SwipeableView
          bg={'transparent'}
          borderRadius={SET_CARD_BORDER_RADIUS}
          deleteButton={DeleteButton}
          height={SET_CARD_HEIGHT - 30}
          key={item.id}
          marginBottom={10}
          onDelete={() => onDelete(item.id)}
          onEdit={() => {}}
          swipeable={editable}
          swipeableHint={false}
          swipeToDelete={true}
          width={ui.screenWidth - 2 * ui.screenPaddingX}
        >
```

**Comment by houssemELbahri** [comment]
fixed in version **0.0.10**
