### ISSUE TITLE
swipeToDelete callback doesn't update when onDelete prop changes

### ISSUE THREAD

**Issue by jlmurphysa** [houssemELbahri/react-native-swipeable-container#6]
**Describe the bug**
Missing dependency. Causes my list to do weird stuff when deleting.

Here is the patch:
```
diff --git a/src/components/SwipeableView.tsx b/src/components/SwipeableView.tsx
index 100eb54..edd9d3b 100644
--- a/src/components/SwipeableView.tsx
+++ b/src/components/SwipeableView.tsx
@@ -71,7 +71,7 @@ export const SwipeableView = ({ children, deleteButton, editButton, height = ITE
                 runOnJS(onDelete)()
             }
         })
-    }, [])
+    }, [onDelete])
```

**Comment by houssemELbahri** [comment]
Hi @melhawnuhra , 
in which cases the onDelete prop changes , can you give me more details ?

**Comment by jlmurphysa** [comment]
Here is a snippet of my use case:

```  
const onDelete = useCallback(
    (id: string) => {
      setReorderedSets(sets.filter(set => set.id !== id))
    },
    [sets, setReorderedSets],
  )
.
.
.
  const renderItem = useCallback(
    ({ item, drag, isActive: dragging }: RenderItemParams<PlayerSet>) => {
      return (
        <SwipeableView
          bg={'transparent'}
          borderRadius={SET_CARD_BORDER_RADIUS}
          deleteButton={DeleteButton}
          height={SET_CARD_HEIGHT - 30}
          key={item.id}
          marginBottom={10}
          onDelete={() => onDelete(item.id)}
          onEdit={() => {}}
          swipeable={editable && !dragging}
          swipeableHint={false}
          swipeToDelete={true}
          width={ui.screenWidth - 2 * ui.screenPaddingX}
          marginStart={ui.screenPaddingX}
        >
```

My `onDelete` function is being updated when its dependencies (`sets/setReorderedSets`) change (by `React.useCallback`).
These changes should propagate to the `SwipeableView`, which they don't currently.

So the result is:
When I delete a set, `SwipeableView` calls a stale delete function using previous values for `sets`, even though they have been updated since.

The PR fixes this, and should not have any adverse effects for current users.

**Comment by houssemELbahri** [comment]
@melhawnuhra , I see that you are using sets directly when filtering you list.

`setReorderedSets(sets.filter(set => set.id !== id))`

It's a bad way in react ,when updating state based on previous state, it could potentially lead to issues ( it's not guaranteed to have the latest state).
the solution is to use an arrow function inside the setReorderedSets .This arrow function receives the previous state (prev) and returns the new state after filtering.

`setReorderedSets(prev => {
            return prev.filter(set => set.id !== id)
        })`

as you can read in the [docs](https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state)

**Comment by jlmurphysa** [comment]
Hi @houssemELbahri ,

Thanks - good point 👍

The PR is still relevant though - `swipeToDelete` operates on the data that was provided when the `onDelete` method was originally given, and does not update when the `onDelete` callback refreshes.

It has a dependency (`onDelete`), and React needs to know to update the callback when this dependency is updated.
