### ISSUE TITLE
onOpen prop for when a card is swiped + ref to call close()

### ISSUE THREAD

**Issue by jlmurphysa** [houssemELbahri/react-native-swipeable-container#8]
**Is your feature request related to a problem? Please describe.**
Currently, multiple cards can have their delete button shown simultaneously.  
We'd like to make it so that: when one is opened, the others close.

**Describe the solution you'd like**
1. `onOpen` callback prop will make it possible for us to implement this functionality.
2.  Ref to the `SwipeableView` so that we can call `close()` on the other open cards

**Additional context**
![image](https://github.com/houssemELbahri/react-native-swipeable-container/assets/6492155/b8273537-d00b-4aa4-a1d4-93566f6e3d80)

**Comment by houssemELbahri** [comment]
Thanks @melhawnuhra  for your feedback , i'm working on that for the next version ,it  will be published soon.

**Comment by houssemELbahri** [comment]
Available in version **0.0.11**
